/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mousepilots.es.core.model;

/**
 *
 * @author jgeenen
 */
public interface EntityManager extends javax.persistence.EntityManager {

     /**
      * Creates an entity with a specified {@code id}. Use this method <em>if
      * and only if</em>
      * the entity has no generated id
      *
      * @param <E> the managed type
      * @param <ID> the id-type
      * @param type the managed type
      * @param id required
      * @return the newly created instance with {@code id} set
      * @throws IllegalArgumentException if the corresponding entity-class is
      * not instantiable or has a generated id
      */
     <E, ID> E create(EntityTypeES<E> type, ID id) throws IllegalArgumentException;

     /**
      * Creates an entity. Use this method <em>if and only if</em> the entity
      * has a generated id. The client-id is auto-generated by the
      * {@link Generator} configured for the entity's id-attribute
      *
      * @param <E> the managed type
      * @param type the managed type
      * @return the newly created instance with {@code id} set
      * @throws IllegalArgumentException if the corresponding entity-class is
      * not instantiable or has a generated id
      */
     <E> E create(EntityTypeES<E> type);

     <E> E create(EmbeddableTypeES<E> type);

     @Override
     public EntityTransactionES getTransaction();

}
